name: composable_cache
description: ComposableCore — TTL cache layer for API responses.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  composable_core:
    path: ../composable_core
  composable_network:
    path: ../composable_network
  get_it: ^8.0.3
  meta: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
